# Generated by Django 6.0.3 on 2026-03-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_materia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materia',
            new_name='Material',
        ),
    ]
