# Generated by Django 6.0.3 on 2026-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_downloadtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paypal_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='paypal_link',
            field=models.URLField(default='https://paypal.me/test'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DownloadToken',
        ),
    ]
