# Generated by Django 6.0.3 on 2026-05-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_paid_remove_order_paypal_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='paypal_link',
        ),
    ]
